# Generated by Django 3.1.3 on 2020-11-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagelabel", options={"ordering": ["-score"]},
        ),
    ]
