# Generated by Django 3.1.3 on 2020-11-15 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_auto_20201115_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelabel',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='recognition.image'),
        ),
    ]
